### ISSUE TITLE
tiny typo on GPT-4 "Reflexion" in leaderboard

### ISSUE THREAD

**Issue by itsPreto** [huybery/Awesome-Code-LLM#2]
First off, if you put this all together yourself I salute you! Great resource! 

Secondly, any reason why Claude/Claude 2 were left out of the ranking? me thinks it would be 3rd on your list:)

**Comment by huybery** [comment]
Thanks for you attention ! I will add Claude / Claude2, but i'm limited by meself and look forward to everyone building together !
