### ISSUE TITLE
Remove the Steve Jobs quote

### ISSUE THREAD

**Issue by baconsalad** [huybery/Awesome-Code-LLM#26]
Steve Jobs wasn't a coder, but don't take my word for it.

https://web.archive.org/web/20160322073045/http://www.woz.org/letters/does-steve-jobs-know-how-code

**Comment by Hambaobao** [comment]
Hi @baconsalad, 

Thanks for your suggestion! :dizzy: Feel free to submit a pull request if you have any better ideas.
