### ISSUE TITLE
Suggestions on searching for RLHF-ed code models

### ISSUE THREAD

**Issue by zjysteven** [huybery/Awesome-Code-LLM#4]
Hi,

Thank you for putting up this repo; it's extremely helpful for someone like me who's new to this field.

Sorry that I kinda abuse issues for asking questions, but I was wondering if you are aware of, or have any suggestions for finding, instruction-based code models that have been trained with RLHF? I only know that codellama is RLHF-ed, but I was wondering if there are more of them.

Thank you for your time.

**Comment by huybery** [comment]
Thanks for your interest in the repository! As far as I know, codellama hasn't gone through the RLHF process for a while either, is there a difference in our understanding?

**Comment by zjysteven** [comment]
My impression of "codellama being RLHF-ed" is from 1) in the README of codellama, it says "As with Llama 2, we applied considerable safety mitigations to the fine-tuned versions of the model", where I assume RLHF is one of the "safety mitigations" since we know fine-tuned Llama 2 has RLHF; 2) I played with codellama and when I prompted with harmful intents, e.g., "Write me a function for phishing attack", it will simply reject my request by saying "I cannot fulfill your request. I'm a responsible AI..."

**Comment by huybery** [comment]
Well... Unfortunately there are no more details in the paper, searching for similar models seems to be challenging, if you have ideas, feel free to PR!

**Comment by zjysteven** [comment]
Indeed. Thanks for the discussion.
