### ISSUE TITLE
Can we initiate a leaderboard section instead of showing single one?

### ISSUE THREAD

**Issue by zhimin-z** [huybery/Awesome-Code-LLM#8]
I found there are a lot of leaderboards on code generation with LLMs.
Such as https://huggingface.co/spaces/bigcode/bigcode-models-leaderboard, https://intercode-benchmark.github.io/, and more. 
Rather than statically showing a single leaderboard, we add a table to include as many as links instead to redirect users to refer based on their preference, just like https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/pull/13.

**Comment by huybery** [comment]
Great idea! I'd appreciate it if you could help build it together.
